#! /bin/sh

sxhkd &

bspc config border_width        0
bspc config window_gap         20

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config auto-cancel		true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a google-chrome desktop=^1 state=floating private=on 
bspc rule -a urxvt state=floating
bspc rule -a libreoffice floating=on private=on
bspc rule -a Display state=floating
bspc rule -a connman-gtk state=floating private=on desktop=^5
bspc rule -a jetbrains-idea-ce state=floating private=on desktop=^3
bspc rule -a jetbrains-studio state=floating private=on desktop=^4
bspc rule -a sublime_text state=floating private=on desktop=^3
bspc rule -a GParted state=floating private=on
