#! /bin/sh

sxhkd &

bspc config border_width        0
bspc config window_gap         20

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

#bspc config auto-cancel		true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a google-chrome:google-chrome desktop=^1 state=floating private=on 
bspc rule -a URxvt:urxvt state=floating
bspc rule -a libreoffice state=floating private=on
bspc rule -a Connman-gtk state=floating private=on desktop=^5
bspc rule -a jetbrains-idea-ce:sun-awt-X11-XFramePeer state=floating private=on desktop=^3
bspc rule -a jetbrains-studio state=floating private=on desktop=^4
bspc rule -a sublime_text state=floating private=on desktop=^3
bspc rule -a GParted state=floating private=on
bspc rule -a Transmission-gtk state=floating private=on desktop=^6
bspc rule -a Agave state=floating private=on desktop=^3
bspc rule -a Hexchat state=floating private=on desktop=^3
bspc rule -a Gimp state=floating private=on desktop=^6
bspc rule -a Eclipse state=floating private=on desktop=^3
bspc rule -a Mainwindow.py state=floating private=on desktop=^4
bspc rule -a Slack state=floating private=on desktop=^4
bspc rule -a Toplevel state=floating private=on desktop=^3
bspc rule -a libreoffice-startcenter state=floating private=on desktop=^4
bspc rule -a luakit state=floating private=on desktop=^1
bspc rule -a feh state=floating private=on
bspc rule -a Google\ Play\ Music\ Desktop\ Player state=tiled private=on desktop=^5
